### ISSUE TITLE
No module named 'antlr4'

### ISSUE THREAD

**Issue by youkotwo** [ToonCrafter/ToonCrafter#31]
hello just have this erros when i try to run "python gradio_app.py":
(env) Z:\ia\toonmaker\ToonCrafter>python gradio_app.py
Traceback (most recent call last):
  File "Z:\ia\toonmaker\ToonCrafter\gradio_app.py", line 4, in <module>
    from scripts.gradio.i2v_test_application import Image2Video
  File "Z:\ia\toonmaker\ToonCrafter\scripts\gradio\i2v_test_application.py", line 3, in <module>
    from omegaconf import OmegaConf
  File "Z:\ia\toonmaker\ToonCrafter\env\lib\site-packages\omegaconf\__init__.py", line 1, in <module>
    from .base import Container, DictKeyType, Node, SCMode
  File "Z:\ia\toonmaker\ToonCrafter\env\lib\site-packages\omegaconf\base.py", line 9, in <module>
    from antlr4 import ParserRuleContext
ModuleNotFoundError: No module named 'antlr4'

i already fixed the issue of decord : ModuleNotFoundError: No module named 'decord' with pip install decord
but this time i can not do in and it is not in requierement.txt
(just folowed the instructions from this guy:
https://www.youtube.com/watch?v=hc5nF6rGa68&t=183s 1:46-3:08)

**Comment by VGrondin** [comment]
pip install antlr4-python3-runtime (if you use python3, which is probably the case)
